{
 "title": "1. Overview",
 "tags": [ "Homelab" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synology RAID Status",
   "type": "table",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidStatus{job=\"snmp\", raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consul tolerance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(consul_autopilot_failure_tolerance{})\n"
    }
   ]
  },
  {
   "title": "Nomad tolerance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_autopilot_failure_tolerance{job=\"nomad\"}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  {
   "title": "Nomad Clients - Resources allocated",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 -\nnomad_client_unallocated_cpu{}\n/\n(nomad_client_allocated_cpu{}\n+ nomad_client_unallocated_cpu{}) * 100",
     "legendFormat": "cpu utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_memory{}\n/\n(nomad_client_allocated_memory{}\n+ nomad_client_unallocated_memory{}) * 100",
     "legendFormat": "memory utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_disk{}\n/\n(nomad_client_allocated_disk{}\n+ nomad_client_unallocated_disk{}) * 100",
     "legendFormat": "disk utilization"
    }
   ]
  },
  {
   "title": "WAN Throughput",
   "type": "timeseries",
   "description": "Spikes on this graph that are missing from the LAN graph indicate gateway-originated traffic, like a scheduled speed test. Rx is on the negative axis.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(unpoller_device_wan_receive_bytes_total{}[$__rate_interval]) * 8",
     "legendFormat": "Bytes Rx"
    },
    {
     "expr": "rate(unpoller_device_wan_transmit_bytes_total{}[$__rate_interval]) * 8",
     "legendFormat": "Bytes Tx"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp\",raidName=\"Volume 1\"}*raidFreeSize{job=\"snmp\",raidName=\"Volume 1\"})",
     "legendFormat": "NAS HDD"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp\",raidName=\"Volume 2\"}*raidFreeSize{job=\"snmp\",raidName=\"Volume 2\"})",
     "legendFormat": "NAS NVMe"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"compute1.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"compute1.home\",mountpoint=\"/\"})",
     "legendFormat": "Compute1"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"compute2.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"compute2.home\",mountpoint=\"/\"})",
     "legendFormat": "Compute2"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"master.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"master.home\",mountpoint=\"/\"})",
     "legendFormat": "Master"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"dmz1.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"dmz1.home\",mountpoint=\"/\"})",
     "legendFormat": "Dmz1"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"dmz2.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"dmz2.home\",mountpoint=\"/\"})",
     "legendFormat": "Dmz2"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"storage.home\", device=\"dm-3\"}[$__rate_interval])",
     "legendFormat": "NAS HDD"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"storage.home\", device=\"dm-1\"}[$__rate_interval])",
     "legendFormat": "NAS NVMe"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"compute1.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Compute1"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"compute2.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Compute2"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"master.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Master"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"dmz1.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Dmz1"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"dmz2.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Dmz2"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{} - node_memory_MemFree_bytes{} - (node_memory_Cached_bytes{} + node_memory_Buffers_bytes{} + node_memory_SReclaimable_bytes{})) / node_memory_MemTotal_bytes{} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Details - compute1.home",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", instance=\"compute1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", instance=\"compute1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', instance=\"compute1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", instance=\"compute1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    }
   ]
  },
  {
   "title": "CPU Details - compute2.home",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", instance=\"compute2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", instance=\"compute2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', instance=\"compute2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", instance=\"compute2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"compute2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    }
   ]
  },
  {
   "title": "CPU Details - dmz1.home",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", instance=\"dmz1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", instance=\"dmz1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', instance=\"dmz1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", instance=\"dmz1.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz1.home\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    }
   ]
  },
  {
   "title": "CPU Details - dmz2.home",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"system\", instance=\"dmz2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=~\".*irq\", instance=\"dmz2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode!='idle',mode!='system',mode!='iowait',mode!='irq',mode!='softirq', instance=\"dmz2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by(instance) (irate(node_cpu_seconds_total{mode=\"iowait\", instance=\"dmz2.home\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"dmz2.home\"}[$__rate_interval])))",
     "legendFormat": "Busy Iowait"
    }
   ]
  },
  { "title": "Nomad Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "nomad_client_allocations_blocked{}",
     "legendFormat": "blocked"
    },
    {
     "expr": "nomad_client_allocations_migrating{}",
     "legendFormat": "migrating"
    },
    {
     "expr": "nomad_client_allocations_pending{}",
     "legendFormat": "pending"
    },
    {
     "expr": "nomad_client_allocations_running{}",
     "legendFormat": "running"
    },
    {
     "expr": "nomad_client_allocations_start{}",
     "legendFormat": "start"
    },
    {
     "expr": "nomad_client_allocations_terminal{}",
     "legendFormat": "terminal"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent{job=\"nomad\", task!~\"connect-proxy.+\"}\n",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nomad_client_allocs_memory_usage{job=\"nomad\", task!~\"connect-proxy.+\"}\n- \nnomad_client_allocs_memory_cache{job=\"nomad\", task!~\"connect-proxy.+\"})\n/\nnomad_client_allocs_memory_allocated{job=\"nomad\", task!~\"connect-proxy.+\"} * 100",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }}"
    }
   ]
  },
  {
   "title": "NFS Send Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_sent_bytes_total{}[$__rate_interval])) by (export)",
     "legendFormat": "{{export}}"
    }
   ]
  },
  {
   "title": "NFS Receive Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_mountstats_nfs_operations_received_bytes_total{}[$__rate_interval])) by (export)",
     "legendFormat": "{{export}}"
    }
   ]
  },
  { "title": "SDN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Upstream request time : heatmap",
   "type": "heatmap",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connection request bytes",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#arch-overview-outlier-detection",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{consul_destination_service!=\"\"} [$__rate_interval:])",
     "legendFormat": "{{consul_source_service}} → {{consul_destination_service}}"
    },
    {
     "expr": "irate(traefik_service_requests_bytes_total{} [$__rate_interval:])",
     "legendFormat": "traefik → {{service}}"
    }
   ]
  },
  {
   "title": "Connection response bytes",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#arch-overview-outlier-detection",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{consul_destination_service!=\"\"} [$__rate_interval:])",
     "legendFormat": "{{consul_destination_service}} → {{consul_source_service}}"
    },
    {
     "expr": "irate(traefik_service_responses_bytes_total{} [$__rate_interval:])",
     "legendFormat": "{{service}} → traefik"
    }
   ]
  }
 ]
}