
  - name: Home Assistant Bridge
    port: {{ env "NOMAD_HOST_PORT_homekit" }}
    advertise_ip: "{{ env "NOMAD_IP_homekit" }}"
    filter:
      include_domains:
        - button
        - climate
        - light
        - switch
        - sensor
