
  - name: Home Assistant Bridge
    port: 21063
    advertise_ip: "192.168.0.3"
    filter:
      include_domains:
        - button
        - climate
        - light
        - switch
        - sensor
